version: '3'
services:
  db:
    image: mysql
    container_name: containerMysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vendadb
    ports:
      - 3307:3306
    networks:
      - apivenda-network

  app:
    image: devjuliana/apivenda
    container_name: containerApp
    restart: always
    env_file:
      - .env
    ports:
      - 9090:8080
    networks:
      - apivenda-network
    depends_on:
      - db

networks:
  apivenda-network:
    driver: bridge
